version: '3.8'

services:
  app: 
    build:
      context: ./Alikin-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/alikin
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - media-volume:/app/uploads
    networks:
      - app-network

  frontend: 
    build:
      context: ./alikin-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"     
      - "443:443"   
    volumes:
      - ./data/nginx/letsencrypt:/etc/letsencrypt 
      - ./data/nginx/www:/var/www/certbot        
    depends_on:
      - app
    networks:
      - app-network

  db: 
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=alikin
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:
  media-volume:
  

networks:
  app-network:
